const {chromium}=require(process.env.PLAYWRIGHT_MODULE);
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.EDGE_PATH});
 const page=await browser.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base='http://127.0.0.1:5063';
 const go=path=>page.goto(base+path);
 const postClick=button=>Promise.all([page.waitForNavigation(),button.click()]);
 for(const width of [360,390,768,1440,1700]){
  await page.setViewportSize({width,height:900});
  for(const path of ['/','/series/1','/search','/search?q=series','/search?q=nothing','/search?q=offline','/settings','/catalog/10?season=1','/people/21?role=directing','/people/20?role=acting']){
   assert.equal((await go(path)).status(),200);
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${width}: ${path} overflow`);
  }
 }
 await page.setViewportSize({width:1440,height:1000});
 await go('/settings');
 assert.equal(await page.locator('input[name=token]').count(),0);
 assert.equal(await page.getByRole('heading',{name:'Ready to explore'}).count(),1);
 await page.screenshot({path:'.qa/settings-desktop.png',fullPage:true});
 await go('/search?q=series');
 assert.equal(await page.locator('.card').count(),4,'Duplicate provider result must be removed');
 await page.getByRole('link',{name:'Explore The Last Horizon',exact:true}).click();
 assert.match(page.url(),/catalog\/10$/);
 assert.equal(await page.getByRole('button',{name:'+ Want to watch',exact:true}).count(),1);
 await page.getByRole('link',{name:/Season 1/}).click();
 assert.equal(await page.locator('.preview-episode').count(),2);
 assert.equal(await page.locator('.spoiler').getAttribute('open'),null);
 await page.screenshot({path:'.qa/catalog-desktop.png',fullPage:true});
 await go('/');assert.equal(await page.locator('.card').count(),4,'Catalog browsing must not add series');
 const cardHeights=await page.locator('.card').evaluateAll(cards=>cards.map(c=>c.getBoundingClientRect().height));
 assert(Math.max(...cardHeights)-Math.min(...cardHeights)<=1,'Library card heights should match');
 await go('/search?q=series');
 const addCard=page.locator('.card').filter({has:page.getByRole('heading',{name:'The Last Horizon',exact:true})});
 await addCard.getByRole('button',{name:'+ Want to watch',exact:true}).click();
 await addCard.getByRole('link',{name:'✓ In your library · Open',exact:true}).waitFor();
 assert.match(page.url(),/search\?q=series$/,'Adding must keep search results open');
 const badCard=page.locator('.card').filter({has:page.getByRole('heading',{name:'Unavailable series',exact:true})});
 await badCard.getByRole('button',{name:'+ Want to watch',exact:true}).click();
 await badCard.locator('.form-message.error').waitFor();
 assert.match(await badCard.innerText(),/temporarily unavailable/);
 assert(await badCard.getByRole('button',{name:'+ Want to watch',exact:true}).isEnabled());
 await go('/catalog/11');
 await page.getByRole('button',{name:'+ Want to watch',exact:true}).click();
 await page.getByRole('link',{name:'✓ In your library · Open',exact:true}).waitFor();
 assert.match(page.url(),/catalog\/11$/);
 await go('/series/1');
 await page.getByLabel('Your private notes').fill('A private episode journal.');
 await page.getByLabel('Your rating').selectOption('9');
 await page.getByLabel('Favorite series').check();
 await postClick(page.getByRole('button',{name:'Save journal'}));
 assert.equal(await page.getByLabel('Your private notes').inputValue(),'A private episode journal.');
 await postClick(page.getByRole('button',{name:'Mark watched',exact:true}).first());
 await page.getByRole('button',{name:'✓ Watched',exact:true}).waitFor();
 await page.getByLabel('Your private notes').fill('Draft survives season opening.');
 let seasonRequests=0;
 await page.route('**/series/1/season/2',async route=>{
  seasonRequests++;
  if(seasonRequests===1) await route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({error:'Temporary season failure'})});
  else await route.continue();
 });
 await page.locator('#season-2 summary').focus();
 await page.keyboard.press('Enter');
 await page.locator('#season-2 .season-feedback.error').waitFor();
 await page.locator('#season-2').getByRole('button',{name:'+ Load episodes'}).click();
 await page.locator('#season-2[data-loaded="1"]').waitFor();
 assert.equal(await page.locator('#season-2 .episode').count(),2);
 assert.equal(await page.getByLabel('Your private notes').inputValue(),'Draft survives season opening.');
 await page.locator('#season-2 summary').click();
 await page.locator('#season-2 summary').click();
 assert.equal(seasonRequests,2,'Reopening cached season must not issue another request');
 assert.equal(await page.locator('#season-2').getAttribute('open'),'');
 assert(await page.getByRole('button',{name:'Upcoming',exact:true}).isDisabled());
 await page.locator('#season-1 summary').click();
 await page.screenshot({path:'.qa/series-detail.png',fullPage:true});
 await page.getByText('Manage this series',{exact:true}).click();
 await postClick(page.getByRole('button',{name:'Remove from library'}));
 await postClick(page.getByRole('button',{name:'Undo removal'}));
 await go('/series/1');
 assert.equal(await page.getByLabel('Your private notes').inputValue(),'A private episode journal.');
 assert.equal(await page.getByLabel('Your rating').inputValue(),'9');
 assert(await page.getByLabel('Favorite series').isChecked());
 assert.equal(await page.getByRole('button',{name:'✓ Watched',exact:true}).count(),1);
 await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('Completed');
 assert(await page.locator('#completion-help').isVisible());
 await page.getByLabel('Your private notes').fill('Completion draft stays safe.');
 await page.route('**/series/1/save',route=>route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({error:'TMDB unavailable. Nothing has changed.'})}));
 await page.getByRole('button',{name:'Save journal'}).click();
 await page.locator('[data-journal-form] .form-feedback.error').waitFor();
 assert.equal(await page.getByLabel('Your private notes').inputValue(),'Completion draft stays safe.');
 await page.unroute('**/series/1/save');
 await postClick(page.getByRole('button',{name:'Save journal'}));
 assert.equal(await page.getByRole('combobox',{name:'Status',exact:true}).inputValue(),'Completed');
 assert.equal(await page.getByRole('button',{name:'✓ Watched',exact:true,includeHidden:true}).count(),3);
 await page.locator('#series-people').getByRole('link',{name:'Alex Morgan Director',exact:true}).click();
 await page.waitForURL('**/people/21?role=directing');
 assert.equal(await page.locator('.filmography .card').count(),2);
 await page.screenshot({path:'.qa/person-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Explore The Last Horizon',exact:true}).click();
 await page.waitForURL('**/catalog/10');
 await page.getByRole('link',{name:'Robin Taylor Alex',exact:true}).click();
 await page.waitForURL('**/people/20?role=acting');
 assert.equal(await page.locator('.filmography .card').count(),1);
 await go('/');
 assert(await page.locator('.card-people a[href="/people/21?role=directing"]').count()>0);
 await page.screenshot({path:'.qa/series-library.png',fullPage:true});
 await page.keyboard.press('Control+k');await page.waitForURL('**/search#search');
 assert(await page.locator('#search').evaluate(e=>e===document.activeElement));
 await page.setViewportSize({width:390,height:844});
 for(const [path,name] of [['/settings','settings'],['/catalog/10?season=1','catalog'],['/','library'],['/series/1','detail'],['/people/21?role=directing','person']]){
  await go(path);await page.screenshot({path:`.qa/${name}-mobile.png`,fullPage:true});
 }
 assert.deepEqual(errors,[]);await browser.close();console.log('50 responsive checks and settings, catalog, additions, journal, episode, Undo, automatic season loading/retry/cache, completion/error recovery, actor/director navigation and keyboard flows passed.');
})().catch(e=>{console.error(e);process.exit(1)});
